language: php

dist: trusty

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

allow_failures:
  - php: nightly

before_script:
  - composer self-update
install:
  - composer install --prefer-source --dev

script:
  - mkdir -p build/
  - vendor/bin/phpunit --coverage-clover build/clover.xml tests/

after_script:
  - php vendor/bin/coveralls -v

